Add HW 25 Buttons
ikirillfedorov/homeWorks pull request #10
Opened 2019-04-01 18:16 UTC by ikirillfedorov

Вот друзья, обстановка становится все веселее, раньше мы с вами только в консоль смотрели, а теперь уже потихоньку приложения собираем :) Задание будет тоже, что я говорил в уроке, а именно - сделать калькулятор :)

Ученик. 

1. Создайте и разместите кнопки цифр и операторов, создайте нужные акшины
2. Добавьте лейбл и создайте соответствующий проперти
3. По нажатию на кнопку на индикатор должна выводиться либо цифра, либо оператор (никаких вычислений - выводим просто значения кнопок)

Студент.

4. Наведите более / менее красоту, можете насоздавать линий (вьюхи с малой шириной)б ставить бэкграундыб используйте картинки если надо и тд. - проявите творчество :)
5. Сделайте так, чтобы когда нажимаешь на цифровую кнопку, то число росло
6. Сделайте кнопку сброса

Мастер.

7. Сохраняйте вводимое число
8. Первую операцию тоже надо сохранить, пока не ввели второе число (используйте енумы!)
9. Когда нажимаешь равно то первое число выболняет операцию над вторым и выводится результат
10. После того, как результат вывелся на экран, он автоматом становиться первым числом и к нему уже можно прибавлять, вычитать и т.д. - как в калькуляторе

Супермен

11. Добавьте точку, теперь можно вводить и дробное число, точка должна работать также, как и точка на обычном калькуляторе (имею в виду, что двух точек в числе быть не может в случае повторного нажатия)
12. С дробным вводом будет посложнее - задание для настоящих суперменов :) 

Жду результатов!

2019-04-03 10:32 UTC, AktuBuct requested changes

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var power:Double = 1.0
тип можно не уточнять, а если уж уточняешь, то после двоеточия пробел

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +        switch String(numberFromLabel) {
больше на if похоже

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    func showResult() {
функции пишем только после того, как описали все проперти, которыми являются и аутлеты

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func present(_ sender: UIButton) {
что делает функция, из названия понятно, что она что-то показывает, на деле что-то перемножает, выглядит странно

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func digitalButtons(_ sender: UIButton) {
экшн называется как будто он возвращает массив каких-то цифр. Что делает эта функция?
Как я понял, она обрабатывает нажатие на клавишу с цифрой. Ну значит и называться должно didPressNumberButton

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func operationButtons(_ sender: UIButton) {
didPressOperationButton

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +            case 11:
заведи тэги операций в енум с raw value и юзайте его, иначе вообще не ясно, что это за цифры

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +        isSecondNumberEmpty = true
можно было сделать secondNumber optional , тогда было бы всего одна переменная, для этих действий.

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +        isDecimal = false
почему? если у нас было decimal и мы нажали + , то у нас уже не decimal? выглядит либо как ошибка логики, либо ошибка архитектуры

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func decimalButton(_ sender: UIButton) {
didPressDotButton

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +        if !isDecimal {
можно и без проверки условия, лишнее действие

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func clearButton(_ sender: UIButton) {
didPressClearButton

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var isLabelEmpty = true
Можно без этого свойства, при Int("")  вернет nil, можно этим и воспользоваться.

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var isDecimal = false
можно сделать computed property, которая будет проверять наличие точки в строке. Тогда не придется постоянно думать о назначении этого свойства

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var operationTag = 0
сделать энум с тагами всех операций и хранить тут понятное значение

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var isSecondNumberEmpty = true
бесполезное свойство, которое только усложняет код

2019-04-03 10:32 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var power:Double = 1.0
подробнее название напиши, не сразу ясно, что это

2019-04-03 19:23 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var power:Double = 1.0
fxd

2019-04-03 19:28 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +        switch String(numberFromLabel) {
fxd

2019-04-03 19:29 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    func showResult() {
fxd

2019-04-03 19:31 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func present(_ sender: UIButton) {
так это кнопка процент % наверное правильно будет convertToPercentage

2019-04-03 19:32 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func digitalButtons(_ sender: UIButton) {
fxd

2019-04-03 19:32 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func operationButtons(_ sender: UIButton) {
fxd

2019-04-03 20:03 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +            case 11:
fxd 
    enum operationTags: Int {
        case divide = 11, multiply, minus, plus, equal
    }

2019-04-03 20:06 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +        isDecimal = false
isDecimal всегда false, кроме когда мы нажимаем кнопку ","
Тут логика если мы не нажали , тогда isDecimal = false
неправильно?

2019-04-03 20:08 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func decimalButton(_ sender: UIButton) {
fxd

2019-04-03 20:11 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +        if !isDecimal {
и правда работает зачем то же я его ставил...

2019-04-03 20:11 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func clearButton(_ sender: UIButton) {
fxd

2019-04-03 20:16 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var power:Double = 1.0
digits  десятичные знаки - наверное будет точнее

2019-04-03 21:51 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func present(_ sender: UIButton) {
Ну написано present, а не percentage. Ну и тогда это didPressPercentageButton

2019-04-03 21:55 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +        isDecimal = false
Ну проверим на практике ;)

2019-04-04 16:06 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    @IBAction func present(_ sender: UIButton) {
fxd

2019-04-04 16:08 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +        isSecondNumberEmpty = true
не понял как сделать (

2019-04-04 16:09 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var isLabelEmpty = true
мне кажется так лучше читается логика

2019-04-04 16:10 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var operationTag = 0
fxd 
    enum operationTags: Int {
        case divide = 11, multiply, minus, plus, equal
    }

2019-04-04 16:13 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var isSecondNumberEmpty = true
убрал

2019-04-04 16:30 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var isDecimal = false
сделал вот так, но чего то появились проблемы с логикой при нажатии кнопки ".", что их решение становится громоздким :( в итоге решил оставить как есть. 

    var isDecimal: Bool {
        return resultLabel.text?.contains(".") ?? false
    }

2019-04-04 19:56 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var isLabelEmpty = true
Нет, так ты должен его постоянно руками менять, где-то можно и забыть это сделать.

2019-04-04 19:58 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var isDecimal = false
а ты там точку или запятую добавляешь? может в этом проблема? так наоборот логики меньше и не нужно постоянно меня состояние этой переменной.

2019-04-04 20:02 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var operationTag = 0
так значит тот должен не 0 хранится: а одно из состояний энума. добавь туда статус none например.

2019-04-04 20:05 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var digits = 1.0
exponentiationLevel лучше бы отразило суть, на край powLevel

2019-04-04 20:07 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +            case operationTags.divide.rawValue:
сделай так, чтоб без rawValue этот свиты был

2019-04-04 20:10 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var numberFromLabel: Double = 0.0
убери аннотации типов, они не нужны

2019-04-04 20:12 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var numberFromLabel: Double = 0.0
Ну если ты его сам менять можешь, а не только с лэйбла получать, то название не подходит

2019-04-04 20:16 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var secondNumber: Double = 0.0
а что из них secondNumber? Смотри, логика какая может быть:

resultNumber - текущий результат всех калькуляций 
operandNumber - операнд с которым нужно произвести калькуляции числа из resultNumber

2019-04-04 20:16 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var secondNumber: Double = 0.0
при этом operandNumber может быть null

2019-04-04 20:27 UTC, AktuBuct requested changes

2019-04-04 20:27 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    enum operationTags: Int {
Енум с большой буквы пишут, в единственном числе.

2019-04-04 20:27 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var operationTag = 0
var operationTag = OperationTag.none

2019-04-04 20:27 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +            case operationTags.divide.rawValue:
в итоге должно быть :

if !isLabelEmpty, let operation = OperationTag(rawValue: sender.tag) {
case .divide: ....

2019-04-04 20:27 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +                numberFromLabel = secondNumber / numberFromLabel
число меняется до того, как ты равно нажал?

2019-04-05 07:14 UTC, AktuBuct commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +                numberFromLabel = secondNumber / numberFromLabel
а, я понял, это чтоб выполнить прошлую операцию

2019-04-05 17:33 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var operationTag = 0
fxd

2019-04-05 17:34 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    enum operationTags: Int {
fxd

2019-04-05 17:36 UTC, ikirillfedorov commented on HW 25 Buttons Superman (Calculator)/HW 25 Buttons Superman (Calculator)/ViewController.swift
> +    var secondNumber: Double = 0.0
fxd

2019-04-05 18:10 UTC, ikirillfedorov commented
rewrite!

2019-04-05 18:10 UTC, closed without merging