Add HW 26 Controls
ikirillfedorov/homeWorks pull request #11
Opened 2019-04-09 16:44 UTC by ikirillfedorov

Ученик. 

1. Расположите тестируюмую вьюху на верхней половине экрана
2. На нижней половине создайте 3 свича: Rotation, Scale, Translation. По умолчанию все 3 выключены
3. Также создайте сладер скорость, со значениями от 0.5 до 2, стартовое значение 1
4. Создайте соответствующие проперти для свитчей и слайдера, а также методы для события valueChanged

Студент.

5. Добавьте сегментед контрол с тремя разными сегментами
6. Они должны соответствовать трем разным картинкам, которые вы должны добавить
7. Когда переключаю сегменты, то картинка должна меняться на соответствующую

Мастер.

8. Как только мы включаем один из свичей, наша вьюха должна начать соответствующую анимацию
(либо поворот, либо скеил, либо перенос). Используйте свойство transform из урока об анимациях
9. Так же следует помнить, что если вы переключили свич, но какойто другой включен одновременно с ним, то вы должны делать уже двойную анимацию. Например и увеличение и поворот одновременно (из урока про анимации)
10. Анимации должны быть бесконечно повторяющимися, единственное что их может остановить, так это когда все три свича выключены

Супермен.

11. Добавляем использование слайдера. Слайдер регулирует скорость. То есть когда значение на 0.5, то скорость анимаций должна быть в два раза медленнее, а если на 2, то в два раза быстрее обычной.
12. Попробуйте сделать так, чтобы когда двигался слайдер, то анимация обновлялась без прерывания, а скорость изменялась в соответствующую сторону.

2019-04-09 19:39 UTC, AktuBuct requested changes

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.h
> +- (IBAction)changeHeroSegmentedControler:(UISegmentedControl *)sender;
это не controller, а control. И controller пишется с 2 L

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +        case 0:
можно было енум сделать

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    self.heroImageView.image = [UIImage imageNamed:@"Tanya"];
не нравится мне, что в двух разных местах имя картинки написано... И вообще, лучше имена картинок тащить в константы.

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                         } completion:^(BOOL finished) {
comleltion в итоге едет по форматированию, лучше пустить с новой строки

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                             [self rotationSwitch:sender];
не очень хорошо, что рекурсию заюзал на метод ibAction. можно подумать над другой реализацией.

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +- (IBAction)rotationSwitch:(UISwitch *)sender {
это функция(действие), а назвал ты это как дуд-то это проперти.

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +- (IBAction)rotationSwitch:(UISwitch *)sender {
ну и ниже экшены в таком же стиле названы

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    self.isHeroIncrease = self.isHeroIncrease ? false : true;
не будь Колей. self.isHeroIncrease = !self.isHeroIncrease

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                                                                              self.isHeroIncrease == true ? 2 : 0.5,
форматирование

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                         } completion:^(BOOL finished) {
форматирование

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                          } completion:^(BOOL finished) {
форматирование

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    self.speedLabel.text = [NSString stringWithFormat:@"Speed: %.02f", sender.maximumValue - sender.value + sender.minimumValue];
объясни расчеты

2019-04-09 19:39 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                             [self rotationSwitch:sender];
и везде ниже

2019-04-10 16:09 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.h
> +- (IBAction)changeHeroSegmentedControler:(UISegmentedControl *)sender;
fxd

2019-04-10 16:18 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +        case 0:
добавил enum

2019-04-10 16:24 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    self.heroImageView.image = [UIImage imageNamed:@"Tanya"];
fxd, если я правильно понял

2019-04-10 16:27 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                         } completion:^(BOOL finished) {
fxd

2019-04-10 16:30 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +- (IBAction)rotationSwitch:(UISwitch *)sender {
fxd

2019-04-10 16:45 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    self.isHeroIncrease = self.isHeroIncrease ? false : true;
fxd :)

2019-04-10 16:45 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                                                                              self.isHeroIncrease == true ? 2 : 0.5,
fxd

2019-04-10 16:45 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                         } completion:^(BOOL finished) {
fxd

2019-04-10 16:45 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                          } completion:^(BOOL finished) {
fxd

2019-04-10 16:46 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    self.speedLabel.text = [NSString stringWithFormat:@"Speed: %.02f", sender.maximumValue - sender.value + sender.minimumValue];
это реверсирует показатели. Но я все переделал, что бы не быть арабом)))

2019-04-10 18:10 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                             [self rotationSwitch:sender];
обсудили, блок выполняется ассинхронно))

2019-04-11 09:27 UTC, AktuBuct requested changes

2019-04-11 09:27 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.h
> +- (IBAction)startAndStopRotationSwitch:(UISwitch *)sender;
start and stop and go and end... Я хз, почему не просто didChangeRotationState или что-то вроде? Да и сам свитч не стартует и не останавливается, он лишь меняет свое положение. Соответственно, ты должен описывать не то, что случилось с объектами на экране от этого, а что случилось с самим контролом. А контрол лишь изменил свое состояние. Он не стартовал и не останавливался.

2019-04-11 09:27 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    TanyaSegment,
при написании кейсов в objC принято сначала писать имя самого енума. Тут соответственнобыло бы SegmentTanya

2019-04-11 09:27 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +} Segment;
SegmentPosition или SegmentState  лучше бы описало происходящее.

2019-04-11 09:27 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    return self.animationSpeed = (self.speedSlider.maximumValue + self.speedSlider.minimumValue) - self.speedSlider.value;
очень сомнительное решение. Ты либо ретурн делай значения, тогда это будет computed property, как в Свифт и строчку `@property (assign, nonatomic) float animationSpeed;` можно будет убрать вовсе. Либо просто сделай метод setAnimationSpeed и без каких-либо ретурнов назначь свойство... Но тогда тебе придется сначала устанавливать его, и только потом забирать, что не будет очень уж удобным, да и setAnimationSpeed который будет что-то устанавливать без входных параметров будет выглядеть крайне странно. Поэтому надо воспользоваться первым советом.

2019-04-11 09:27 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +@property (strong, nonatomic) UIImage *tanyaPicture;
Может быть и нет смысла хранить в оперативке сами картинки, было бы вполне достаточно хранить имена, а потом уже цеплять картинку по имени. В рамках ДЗ, не критическая правка.

2019-04-11 09:27 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    NSLog(@"print");
ну принт этот больше не нужен уже =)

2019-04-11 09:27 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +            [UIView animateWithDuration:self.animationSpeed
что-то весь блок кода уехал куда-то

2019-04-11 16:13 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.h
> +- (IBAction)startAndStopRotationSwitch:(UISwitch *)sender;
понял, спасибо за развернутый комментарий

2019-04-11 16:14 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +@property (strong, nonatomic) UIImage *tanyaPicture;
хм... точно, чето сам не догодался)))

2019-04-11 16:15 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    TanyaSegment,
точно перепутал)) Помню ты уже комментировал такой момент

2019-04-11 16:16 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +} Segment;
fxd

2019-04-11 16:21 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    return self.animationSpeed = (self.speedSlider.maximumValue + self.speedSlider.minimumValue) - self.speedSlider.value;
точно я изначальнно и хотел сделать computed property но нахуракал какую то жесть)))
fxd
return self.speedSlider.maximumValue + self.speedSlider.minimumValue - self.speedSlider.value

2019-04-11 16:22 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    NSLog(@"print");
упс)))
fxd

2019-04-11 16:23 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +            [UIView animateWithDuration:self.animationSpeed
КАК?!??!!? КАК ТЫ ЭТО ЗАМЕЧАЕШЬ!?!?!??!? ))))))

2019-04-11 19:49 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +            [UIView animateWithDuration:self.animationSpeed
как? да просто... В коммите огромный кусок кода удален и такой же огромный вставлен. Значит либо было неправильно отформатировано и ты исправил, либо наоборот. Но я бы скорее всего и так заметил бы.

2019-04-11 20:00 UTC, AktuBuct requested changes

2019-04-11 20:00 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    SegmentTanya,
А почему кейсы не содержат полное имя енума? SegmentStateTanya

2019-04-11 20:00 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +
коммент по приколу... А зачем 4 пробела сюда воткнул?

2019-04-11 20:00 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                             [self didChangeRotationState:sender];
и вот тут уже пошла несостыковка... Стейт не менялся, а функцию вызываешь... Поэтому я и говорил, что нехорошо, когда экшены вызываются из кода... Лучше всю логику вынести в отдельную функцию и вот её уже циклически перезапускать. Еще, вместо рекурсии, всегда можно while заюзать.

2019-04-11 20:00 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +- (IBAction)didChangeSscaleState:(UISwitch *)sender {
sssssssssssscale

2019-04-11 20:00 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                                                                                   self.isHeroIncrease == true ? 2 : 0.5,
true == true ? true : true != true ? false : true... Ну ты понял

2019-04-11 20:00 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/Base.lproj/Main.storyboard
> -    <device id="retina6_1" orientation="portrait">
Вот пора тебя приучать наверное, если файл или какие-то строки не требуют изменений в рамках коммита, то не надо их коммитить. Какая мне разница, да и проекту в целом, что ты переключил режим сториборда

2019-04-11 20:00 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/Base.lproj/Main.storyboard
> +                                    <action selector="didChangeSscaleState:" destination="BYZ-38-t0r" eventType="valueChanged" id="by4-X0-WUp"/>
вот это изменение, например, нужное

2019-04-11 20:00 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/Base.lproj/Main.storyboard
> -                        <rect key="frame" x="0.0" y="0.0" width="414" height="896"/>
а вот это нет.

2019-04-11 20:27 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +
кстати, прикол приколом, но у меня такой pr бы был бы отклонен

2019-04-12 04:05 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/Base.lproj/Main.storyboard
> -    <device id="retina6_1" orientation="portrait">
понял

2019-04-12 04:05 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/Base.lproj/Main.storyboard
> +                                    <action selector="didChangeSscaleState:" destination="BYZ-38-t0r" eventType="valueChanged" id="by4-X0-WUp"/>
понял

2019-04-12 04:08 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +    SegmentTanya,
fxd

2019-04-12 04:08 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +
Странно, но у меня нет 4 пробелов в проекте

2019-04-12 04:38 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                             [self didChangeRotationState:sender];
Вынес в отдельную функцию, теперь при изменении стейта свича проверяет если вкл или выкл, если вкл тогда запускает рекурсивную функцию startPictureRotation, и останавливает когда свич выкл.
По поводу while тоже была такая идея, пробовал реализовать, но не вышло почем то while не ждет пока пройдет анимация, а сразу запускает функцию пока свич в состоянии вкл.

2019-04-12 04:38 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +- (IBAction)didChangeSscaleState:(UISwitch *)sender {
fxd))

2019-04-12 04:39 UTC, ikirillfedorov commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                                                                                   self.isHeroIncrease == true ? 2 : 0.5,
fxd))))

2019-04-13 17:20 UTC, AktuBuct commented on HW 26 Controls superman/HW 26 Controls superman/ViewController.m
> +                             [self didChangeRotationState:sender];
А, ну да, у нас же анимация асинхронно уходит, поэтому функция проходит до конца и вызывается новый цикл while. Можно через него делать, но с ручным управлением очередью, но тему потоков ты уже проходил, можно было бы и сделать через потоки эту задачу для практики

2019-04-13 17:26 UTC, AktuBuct approved these changes
можешь мерджить

2020-01-26 14:28 UTC, merged