Add HW 27-28 TextField
ikirillfedorov/homeWorks pull request #12
Opened 2019-04-15 18:53 UTC by ikirillfedorov

Создаем форму для регистрации студента.

Ученик. 

1. Создайте поля (и лейблы напротив как в уроке): имя, фамилия, логин, пароль, возраст, телефон, имеил адрес.
2. Установите правильные виды клавиатур для каждого текстового поля.
3. У всех текстовых полей кроме последнего кнопка ретерн должна быть NEXT, а у последнего DONE.
4. Осуществите переход по кнопкам NEXT и уберите клаву с экрана кнопкой DONE. 
5. Каждое поле при нажатии должно иметь кнопку очистки 

Студент

6. Совет, чтобы осуществить переход по NEXT без проверки тонны пропертей, попробуйте использовать UIOutletCollection
7. Создайте соответствующие каждому текстовому полю UILabel чтобы выводить туда информацию из текстовых полей. Сделайте их мелкими и другого цвета.
8. По изменению текста (даже буквы) обновляйте эти лейблы (не забудте про CLEAR button)

Мастер

9. Для поля ввода телефона используйте мой код из видео, можете поместить его в какой-то оотдельный метод если надо
10. Этот код должен работать только для поля телефона и не для какого другого

Супермен

11. Для поля ввода имеила ограничте ввод символов недопустимых в адресе
12. Более того, сибвол "@" может быть введен только 1 раз
13. установите разумное ограничение для этого поля

2019-04-15 21:35 UTC, AktuBuct requested changes

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +class ViewController: UIViewController, UITextFieldDelegate {
поддержку делегата тащи в отдельное расширение, уже делал подобное замечание на рисовалке

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    enum TextFieldType: Int {
енум в перемешку с функциями, серьезно? либо тащи его в самое начало класса, чтоб сразу было видно его, либо выноси в отдельный extension.

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    @IBAction func actionTextChanged(_ sender: UITextField) {
изменен в прошедшем времени, звучит как пассив, а это экшн. didChange лучше подходит

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        case firstName = 0, lastName, login, password, age, phoneNumber, email
в одну строку конечно можно, но лучше на разных

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +                textFieldsCollection.last?.resignFirstResponder()
textField.resignFirstResponder()

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        var validationSet = CharacterSet.init(charactersIn: "!#$%&'*+-/=?^`{|}~[]; ")
init можно не писать

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        var validationSet = CharacterSet.init(charactersIn: "!#$%&'*+-/=?^`{|}~[]; ")
наверняка есть готовый сет, либо взять сет букв и доавить к нему разрешенные символы

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        guard components.count <= 1 else { return false }
во-первых, да гварда можно собрать в один через запятую.
во-вторых гвард используется для раннего выхода из функции, тут их можно было заменить простым ифом
в-третьих почему не просто return components.count > 1 || emailTextLenght >= emailCharactersLimit || string != "". ну и каждое условие, естественно, с новой строки
в-четвертых, string.isEmpty() можно заюзать вместо сравнивания строки с ""

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if components.count > 1 {
guard

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        var newString = (textField.text as NSString?)?.replacingCharacters(in: range, with: string) ?? string
что тут происходит?

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if newString.count > localNumberMaxLength + areaCodeMaxLength + countryCodeMaxLength {
guard

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        textLabelsCollection[TextFieldType.phoneNumber.rawValue].text = resultString
А если массив короче будет?

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    func phoneTextFieldChanged(_ string: String, _ textField: UITextField, _ range: NSRange) -> Bool {
очень длинная функция, разделить бы на несколько логических блоков...

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if textField.isEqual(textFieldsCollection[TextFieldType.email.rawValue]) {
1, если массив будет короче - все упадет.
2, textField.isEqual проверит, только на то, что параметры первого текствифла равны параметру второго, если у тебя их будет 2 с одинаковыми параметрами, то они для него будут идентичны, что в данном контексте неверно, лучше уж тогда сравнивать тот же это объект в памяти или нет. адрес памяти можно сравнить через ===

2019-04-15 21:35 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        switch textField.tag {
а еще можно было инициализировать тип из тага по raw value и свитчить уже по честному енуму.

2019-04-17 16:20 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    enum TextFieldType: Int {
перенес в начало класса

2019-04-17 16:21 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    @IBAction func actionTextChanged(_ sender: UITextField) {
fxd

2019-04-17 16:22 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        case firstName = 0, lastName, login, password, age, phoneNumber, email
fxd

2019-04-17 16:23 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +                textFieldsCollection.last?.resignFirstResponder()
fxd

2019-04-17 16:25 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        var validationSet = CharacterSet.init(charactersIn: "!#$%&'*+-/=?^`{|}~[]; ")
fxd

2019-04-17 16:41 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        var validationSet = CharacterSet.init(charactersIn: "!#$%&'*+-/=?^`{|}~[]; ")
готового сета под майл адрес не нашел, сделал буквы + разрешенные символы

2019-04-17 17:00 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        guard components.count <= 1 else { return false }
Тут по логике 1 оператор && должен быть, но в целом да круто! Код упростил и понимание проще стало)

return components.count <= 1 &&
           emailTextLenght < emailCharactersLimit ||
           string.isEmpty

2019-04-17 17:02 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if components.count > 1 {
ах да точно)) 
Кстати, если тебе интересно я только в этом задании нормально понял как гвард работает))))

2019-04-17 17:17 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if newString.count > localNumberMaxLength + areaCodeMaxLength + countryCodeMaxLength {
fxd

2019-04-17 17:26 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        textLabelsCollection[TextFieldType.phoneNumber.rawValue].text = resultString
Если я тебя правильно понял:
guard let text = textField.text as NSString? else { return false }
var newString = text.replacingCharacters(in: range, with: string)

2019-04-17 17:34 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    func phoneTextFieldChanged(_ string: String, _ textField: UITextField, _ range: NSRange) -> Bool {
вынес создание localNumber, areaNumber и countryNumber в отдельную функцию

2019-04-17 17:39 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        guard components.count <= 1 else { return false }
components.count <= 1 это же false должен был быть... следи за выражением.
во втором выражении тоже перевернуть надо и в третьем... Внимательнее, Кирилл

2019-04-17 17:42 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        textLabelsCollection[TextFieldType.phoneNumber.rawValue].text = resultString
не понял, как это относится к этому замечанию

2019-04-17 17:49 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if textField.isEqual(textFieldsCollection[TextFieldType.email.rawValue]) {
1. Я понимаю, тогда он обратится к индексу, которого нет в массиве и все упадет. Но это же исключено в данном случае. 
2. Крут, а я и забыл уже про это оператор)))

2019-04-17 17:53 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        switch textField.tag {
не понял как это сделать?

2019-04-17 18:35 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        switch textField.tag {
сделал, после переписки))

2019-04-17 18:36 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        var newString = (textField.text as NSString?)?.replacingCharacters(in: range, with: string) ?? string
Если я тебя правильно понял:
guard let text = textField.text as NSString? else { return false }
var newString = text.replacingCharacters(in: range, with: string)

2019-04-17 18:41 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        guard components.count <= 1 else { return false }
обсудили fxd

2019-04-17 19:11 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if textField.isEqual(textFieldsCollection[TextFieldType.email.rawValue]) {
исключено сейчас, а завтра кто-то зайдет и удалит какое-то поле ... ну или еще что.

2019-04-17 19:38 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +class ViewController: UIViewController, UITextFieldDelegate {
перенес вместе с методами делегата в extension

2019-04-18 09:01 UTC, AktuBuct commented
на все отписался, что поправил, а коммита нет.

2019-04-18 16:33 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if textField.isEqual(textFieldsCollection[TextFieldType.email.rawValue]) {
поставил guard

2019-04-18 16:33 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        textLabelsCollection[TextFieldType.phoneNumber.rawValue].text = resultString
поправил, guard textFieldsCollection.count > TextFieldType.email.rawValue else { return false }

2019-04-18 17:15 UTC, AktuBuct requested changes

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +extension ViewController: UITextFieldDelegate {
экстеншены пишутся после класса, а не до. Это логично, так как ты сначала создаешь класс и его базовую реализацию и только потом расширяешь

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if textField === textFieldsCollection[TextFieldType.email.rawValue] {
не принципиально сейчас, но опять небезопасное обращение к массиву, все упадет, если там будет меньше элементов.

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        case lastName = 1
для всех кейсов rawValue не обязательно указывать явно, достаточно для одного первого, если отсечт идет не с нуля. А если с нуля, вроде, вообще можно не указывать его явно

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
>      var emailCharactersLimit = 30
явно private и судя по всему let. и вообще, больше похоже на константы. Один из способов вынести константы красиво, является расширение класса с выносом всех констант туда
Пример: 

```
private extension YourClass {
    enum Constants {
        static let address = "skjhdfkjshf"
        static let limit = 30
    }
}
```

Почему енум? потому, что для него не получится сделать инстанс, если в нем нет кейсов, как итог, ты получаешь всегда статическое использования этого енума и обращаешься из кода так Constants.limit

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    @IBAction func didChange(_ sender: UITextField) {
didChange что? я только про глагол писал. didChangeText уж тогда

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
>              if textField.isEqual(textFieldsCollection.last) {
так и не сделал проверку под адресу объекта. Если будет еще одно поле с аналогичными параметрами, то иф сработает на нем

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        validationSet.insert(charactersIn: "_-@.1234567890")
с цифрами тоже есть сет. Можно было взять сет букв, добавить к нему сет цифр + 4 символа

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if resultString.count > 3 {
3 в константы

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        guard let text = textField.text as NSString? else { return false }
можно объединить с прошлым гвардом в один

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    fileprivate func makeAreaNumber(_ newString: String, _ localNumberMaxLength: Int, _ areaCodeMaxLength: Int, _ countryCodeMaxLength: Int, _ resultString: inout String) {
все ограничения номера лучше утащить в константы, не придется их потом по функциям прикидывать и если поменяется этот стандарт не придется их по файлу искать, спустишься в список констант и поменяешь

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    fileprivate func makeLocalNumber(_ resultString: inout String, _ newString: String, _ localNumberLength: Int) {
если функция называется make что-то там, она должна создавать и возвращать. У тебя же это скорее configureLocalNumber. Выбери одно из двух решений и сделай так

2019-04-18 17:15 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        let localNumberMaxLength = 7;
все это в константы

2019-04-18 17:18 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +extension ViewController: UITextFieldDelegate {
логично... fxd

2019-04-18 17:19 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if textField === textFieldsCollection[TextFieldType.email.rawValue] {
понял, не правил

2019-04-18 17:22 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        case lastName = 1
работает вообще без указания, fxd

2019-04-18 17:34 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    @IBAction func didChange(_ sender: UITextField) {
fxd

2019-04-18 17:34 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
>      var emailCharactersLimit = 30
вынес все константы в расширение и энумчик

2019-04-18 17:42 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
>              if textField.isEqual(textFieldsCollection.last) {
блин поправил только в одном месте а он в 2 местах.
fxd

2019-04-18 18:01 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        validationSet.insert(charactersIn: "_-@.1234567890")
var validationSet = CharacterSet.letters.union(CharacterSet.decimalDigits)
fxd

2019-04-18 18:02 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        if resultString.count > 3 {
fxd

2019-04-18 18:08 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        guard let text = textField.text as NSString? else { return false }
guard let text = textField.text as NSString?, components.count <= 1 else { return false }

2019-04-18 18:18 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    fileprivate func makeAreaNumber(_ newString: String, _ localNumberMaxLength: Int, _ areaCodeMaxLength: Int, _ countryCodeMaxLength: Int, _ resultString: inout String) {
круто! все работает и очень удобно не надо длинные функции делать

2019-04-18 18:20 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +    fileprivate func makeLocalNumber(_ resultString: inout String, _ newString: String, _ localNumberLength: Int) {
fxd

2019-04-18 18:20 UTC, ikirillfedorov commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        let localNumberMaxLength = 7;
fxd

2019-04-18 18:59 UTC, AktuBuct approved these changes
можешь мерджить

2019-04-18 18:59 UTC, AktuBuct commented on HW 27-28 TextField/HW 27-28 TextField/ViewController.swift
> +        area = " (\(area)) "
не понял, зачем это на 2 действия разбито, но фиг с ним

2019-04-18 19:04 UTC, merged