Add HW 31-32 UITableView editing
ikirillfedorov/homeWorks pull request #15
Opened 2019-05-26 15:56 UTC by ikirillfedorov

Ученик
1. Создайте контроллер с таблицей в коде без сторибордов.
2. Заполните таблицу данными на свое усмотрение
3. Объедините данные в группы (секции)
Студент.
4. Реализуйте механизм перемещения данных между рядами и секциями
5. Вы должны четко понимать что и как работает и в какой последовательности поэтому повторяйте задание пока вы полностью не освоите этот механизм
Мастер.
6. Реализуйте удаление рядов
Супермен
7. Реализуйте механзм добавления секций и рядов на ваше усмотрение

2019-05-26 18:58 UTC, AktuBuct reviewed
Очень много небезопасных обращений к элементу массива по индексу, лучше бы их заменить на что-то более безопасное + много обращений по индекс - 1 из-за той злосчастной кнопки, соответственно это надо тоже как-то унифицировать, чтоб весь код не сломался и не пришлось переписывать, если захочешь добавить ещё одну кнопку или удалить её.

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +let models = ["Volga", "Gaz", "Volvo", "Mazda"]
плохо, что это глобальные константы, лучше было бы их приватными оставить

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +class Car: NSObject {
Зачем NSObject?

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +    var model = String()
Зачем инициализируешь пустыми значениями?

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +        car.driver = drivers.randomElement() ?? "No driver"
можно было это все в конструкторе сделать

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Garage.swift
> +class Garage: NSObject {
NSObject

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Garage.swift
> +    var name: String!
почему небезопасные значения?

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +class MyViewController: UIViewController {
а что не назвал адекватно? Например, GarageListViewController

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +class MyViewController: UIViewController {
А что не унаследовал от UITableViewController?

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        super.loadView()
почитай доку по этому методу

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        self.tableView = tableView
зачем выше инициализировал таблицу и тут же её заменил?

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        let tableView = UITableView.init(frame: frame, style: UITableView.Style.grouped)
int можно не писать

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        let tableView = UITableView.init(frame: frame, style: UITableView.Style.grouped)
UITableView.Style.grouped -> .grouped

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +    var tableView = UITableView()
зачем var?

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        var barButtonItem = UIBarButtonItem.SystemItem.done
.done

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +            barButtonItem = UIBarButtonItem.SystemItem.edit
.edit

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        if isEditing {
а что через тернарник не сделал?

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        let editButton = UIBarButtonItem(barButtonSystemItem: barButtonItem, target: self, action: #selector(actionEdit))
это же может быть не только edit button, но еще и one

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        garage.name = "Garage #\(garageArray.count + 1)"
похоже на тот самый баг

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        var cell = UITableViewCell()
а зачем тут пустую ячейку инициализировал и потом заменил? Можно было просто оставить let cell: UITableViewCell

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        let sourceGrop = garageArray[sourceIndexPath.section]
Group

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +            tableView.deleteRows(at: [indexPathForDelete], with: UITableView.RowAnimation.left)
.left

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +extension MyViewController: UITableViewDelegate, UITableViewDataSource {
хм... А методы Data source раположены за пределами этого экстеншена выше ;) Рекомендую разделить это добро на 2 расширения

2019-05-26 18:58 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        if indexPath.row == 0 {
может 0 заменить на константу addCaCellIndexr? А то встречается много где

2019-05-27 16:30 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +let models = ["Volga", "Gaz", "Volvo", "Mazda"]
сделал приватными

2019-05-27 16:43 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +    var model = String()
fxd

2019-05-27 16:44 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +        car.driver = drivers.randomElement() ?? "No driver"
реализовал через инициализатор

2019-05-27 16:44 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Garage.swift
> +class Garage: NSObject {
fxd

2019-05-27 16:44 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +class Car: NSObject {
убрал родителя

2019-05-27 17:00 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Garage.swift
> +    var name: String!
переделал немного, убрал небезопасные значения и добавил инициализатор

2019-05-27 17:02 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +class MyViewController: UIViewController {
переименовал

2019-05-27 17:04 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +class MyViewController: UIViewController {
по уроку надо было наследоваться от viewController 
в следующих уроках со слов Леши будем UITableViewController делать

2019-05-27 17:10 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        super.loadView()
Прочитал в оригинале(в меру своих способностей) и гуглтраслейт. 
Понял, что:
Your custom implementation of this method should not call super.
You should never call this method directly.

2019-05-27 17:14 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        self.tableView = tableView
мысли пока так идут, не оптимизировано))) 
fxd

2019-05-27 17:14 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        let tableView = UITableView.init(frame: frame, style: UITableView.Style.grouped)
fxd

2019-05-27 17:19 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +    var tableView = UITableView()
Так меняю же вроде
self.tableView = UITableView(frame: view.bounds, style: .grouped)

2019-05-27 17:20 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        var barButtonItem = UIBarButtonItem.SystemItem.done
тут почему то так не работает.
Reference to member 'done' cannot be resolved without a contextual type

2019-05-27 17:20 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +            barButtonItem = UIBarButtonItem.SystemItem.edit
тут почему то так не работает.
Reference to member 'done' cannot be resolved without a contextual type

2019-05-27 17:24 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        if isEditing {
fxd 
let barButtonItem = isEditing ? UIBarButtonItem.SystemItem.edit : UIBarButtonItem.SystemItem.done

2019-05-27 17:29 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        let editButton = UIBarButtonItem(barButtonSystemItem: barButtonItem, target: self, action: #selector(actionEdit))
ХЗ как назвать, посмотрел несколько примеров обычно все таки обозначают editButton несмотря на, что она и может быть done. 
В общем решил назвать так rightBarButton

2019-05-27 17:31 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        garage.name = "Garage #\(garageArray.count + 1)"
тут оставил все как есть а вот "Гараж №0" убрал, теперь с 1 начинается
let garage = Garage(name: "Garage #\(i + 1)", cars: [Car]())

2019-05-27 17:31 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        var cell = UITableViewCell()
fxd

2019-05-27 17:32 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        let sourceGrop = garageArray[sourceIndexPath.section]
купил гавноклаву вот результат :(

2019-05-27 17:33 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +            tableView.deleteRows(at: [indexPathForDelete], with: UITableView.RowAnimation.left)
fxd

2019-05-27 17:40 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +extension MyViewController: UITableViewDelegate, UITableViewDataSource {
разбил на 2 расширения.

2019-05-27 18:01 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        if indexPath.row == 0 {
вывел в константу addCarCellIndex и numberOfSystemCells

2019-05-27 18:48 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +class MyViewController: UIViewController {
ok

2019-05-27 18:50 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/MyViewController.swift
> +        var barButtonItem = UIBarButtonItem.SystemItem.done
А, потому что тогда не известно что это за тип будет, все верно

2019-05-27 19:03 UTC, AktuBuct requested changes

2019-05-27 19:03 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/AppDelegate.swift
> +        let navContoller = UINavigationController.init(rootViewController: viewController)
зачем опять int оставил?

2019-05-27 19:03 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +    var tableView = UITableView()
ну блин, опять какой-то объект заглушка... Либо делай опциональными, либо var tableView: UITableView!

2019-05-27 19:03 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +        self.tableView = UITableView(frame: view.bounds, style: .grouped)
да настройка в View вполне была возможна и в loadView, просто у этого метода не надо вызывать super и в нем ненадо ничего пихать кроме настройки вьюхи. Т.е. создать табличку и положить её на View там вполне возможно. А вот наполнять уже таблицу данными там точно не стоит

2019-05-27 19:03 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +        let rightBarButton = UIBarButtonItem(barButtonSystemItem: barButtonItem, target: self, action: #selector(actionEdit))
Ну вот вообще не вижу смысла промежуточную переменную делать

let rightBarButton = UIBarButtonItem(barButtonSystemItem: isEditing ? .edit : .done, 
              target: self,
 action: #selector(actionEdit))

2019-05-27 19:03 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +        let barButtonItem = isEditing ? UIBarButtonItem.SystemItem.edit : UIBarButtonItem.SystemItem.done
Вот тут скорее всего сработало бы так 

let barButtonItem = isEditing ? UIBarButtonItem.SystemItem.edit : .done

или так 

let barButtonItem: UIBarButtonItem.SystemItem = isEditing ? .edit : .done

2019-05-27 19:03 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +        let sourceGrop = garageArray[sourceIndexPath.section]
клавиатура клавиатурой, а что не исправил?

2019-05-27 19:03 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +    init() {
А мне вот нравилось randomCar. Просто сделай инициализатор с конструктором и верни функцию randomCar, которая будет вызывать этот инициализатор

2019-05-27 19:20 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +    init() {
fxd

2019-05-27 19:23 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +        let sourceGrop = garageArray[sourceIndexPath.section]
поправил теперь

2019-05-27 19:27 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +        let barButtonItem = isEditing ? UIBarButtonItem.SystemItem.edit : UIBarButtonItem.SystemItem.done
Вот так только работает:
let barButtonItem = isEditing ? UIBarButtonItem.SystemItem.edit : .done

2019-05-27 19:32 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +        let rightBarButton = UIBarButtonItem(barButtonSystemItem: barButtonItem, target: self, action: #selector(actionEdit))
fxd

2019-05-27 19:33 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +        self.tableView = UITableView(frame: view.bounds, style: .grouped)
понял

2019-05-27 19:36 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +    var tableView = UITableView()
var tableView: UITableView!

2019-05-27 19:40 UTC, ikirillfedorov commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/AppDelegate.swift
> +        let navContoller = UINavigationController.init(rootViewController: viewController)
забыл appDelegate почистить
fxd

2019-05-27 21:15 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +        let barButtonItem = isEditing ? UIBarButtonItem.SystemItem.edit : UIBarButtonItem.SystemItem.done
врунишка =)

2019-05-27 21:41 UTC, AktuBuct reviewed
Все что написано, можешь принять в качестве рекомендаций на будущее и не исправлять.

2019-05-27 21:41 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +        let rightBarButton = UIBarButtonItem(barButtonSystemItem: isEditing ? .edit : .done, target: self, action: #selector(actionEdit))
научись ты длинный код на строки бить, тем более там даже немного логики есть, сложно читать же

2019-05-27 21:41 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Car.swift
> +    init(model: String, year: Int, driver: String) {
а почему, кстати, машина это класс? Больше на структуру похоже. И инициализатор можно было бы не писать.

2019-05-27 21:41 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/Models/Garage.swift
> +class Garage {
это скорее структура

2019-05-27 21:41 UTC, AktuBuct commented on HW 31-32 UITableView Editing/HW 31-32 UITableView Editing/GarageListViewController.swift
> +            DispatchQueue.main.asyncAfter(wallDeadline: .now() + 0.3) {
просто на всякий случай скажу, обычно так не делают =) Есть более гуманные способы решения этого вопроса. Об одном из них ты уже даже доклад слышал

2020-01-26 14:28 UTC, merged