Add HW 24 Drawings Superman
ikirillfedorov/homeWorks pull request #9
Opened 2019-03-30 08:42 UTC by ikirillfedorov

7. Сделайте простую рисовалку - веду пальцем по экрану и рисую :)

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +protocol DrawingViewDelegate {
вот не похоже на delegate

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +protocol DrawingViewDelegate {
если это делегат, то должны методы выглядит примерно так:
drawingView(_ drawingView:DrawingView, didDrawPoint: CGPoint) 

Функция делегата - сообщать о том, что что-то случилось на твоем объекте. Ты же получаешь какие-то значения. Соответственно, это просто должно быть обычным свойством в твоем классе, но никак не делегатом. Соответственно и в качестве протокола не совсем понятно зачем это держать.

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        let color = UIColor.init(red: self.delegate.redColor,
self можно не писать, init можно не писать. Весь код ниже тоже проверь на эти признаки

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        UIGraphicsEndImageContext() // image ends
есть крутая штука, называется defer сделано как раз для того, чтоб не забыть выполнить какое-то обязательное действие при выходе из функции. Вот UIGraphicsEndImageContext() можно туда поместить. А так как у тебя там будет гвард, то это добавит удобство тем, что не придется UIGraphicsEndImageContext() писать дважды(для обычного выхода из функции и для ошибочного кейса гвардии)

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        context?.move(to: fromPoint)
вместо кучи раз использования обшивала можно было просто один раз распаковать значение в гварде

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        var imageRect = CGRect(x: 0, y: 0, width: mainView.frame.width, height: mainView.frame.height)
эти 2строчки уже видел. Можно было сделать функцию makeImageRect(in view: UIView) -> CGRect

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        imageRect = imageRect.integral
не совсем понятно, зачем создавать рект и тут же его перезаписывать другим. можно было выполнить операцию в одно действие да еще и рект был бы let, а let, как известно, работает быстрее

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        mainView.image?.draw(in: imageRect, blendMode: .normal, alpha: 1)
такие же замечания, как и к функции выше, распаковать опшиналы, если используются более одного раза и юзать defer для закрытия контекста

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        let color = UIColor.init(red: self.delegate.redColor,
это уже видел, кажется пора научить твой "делегат", который на самом деле не делегат, возвращать сразу цвет

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        var imageRect = CGRect(x: 0, y: 0, width: self.frame.width, height: self.frame.height)
третий раз

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        UIGraphicsEndImageContext() // image ends
тут все тожже самое

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +    var lastPoint  =  CGPoint()
не надо делать это "крутое" форматирование с выравниванием, а то потом при добавлении переменной с более длинным названием в гите мифы будут страдать, так как вместо изменения одной строчки, будешь менять все

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +class ViewController: UIViewController, DrawingViewDelegate {
ну вместо delegate можно было сделать что-то вроде DrawingViewColorSource

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +    // MARK: - protocole's properties
Лучше написать какой протокол, а то их может быть несколько, например: // MARK: - DrawingViewDelegate

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +class ViewController: UIViewController, DrawingViewDelegate {
лучше поддержку протокола вынести в extension, так он будет логически отделен от всего остального кода контроллера.

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +    var redColor   =  CGFloat()
это не цвет, а уровень насыщенности данного цвета

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +
лишних пропусков не надо

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +            self.view.backgroundColor = UIColor.init(patternImage: image)
init можно не писать

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +    func addGestureRecognizer(direction: UISwipeGestureRecognizer.Direction) {
addSwipeRecognizer

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        default:
свиты неисчерпывающий, соответственно двойной свайп в любую сторону, переданный в эту функцию будет прятать панель, лучше было указать явно, что прятать при Свайпе вниз

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        swiped = false
свапнуто... это прошедшее время.. Скорее должно быть что-то, что будет отражать суть происходящее, а происходит событие при котором есть активный свайп, который сейчас в процессе. hasActiveSwipeAction например или что-то более короткое, но отражающую этот же смысл

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        let touch = touches.first!
как уже говорил, стараемся отказываться от ! в коде

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        let currentPoint = touch.location(in: tempDrawingView)
чуть выше тоже есть получение поинта из тачей, можно объединить логику

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        refreshValues()
зачем пересчитывать все, когда поменялось что-то одно?

2019-04-03 09:59 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        opacityValue.text = String.init(format: "%1.1f", opacity)
init можно не писать

2019-04-03 10:07 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +protocol DrawingViewDelegate {
1

2019-04-03 10:08 UTC, AktuBuct reviewed
Надо исправлять =)

2019-04-03 17:02 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        let color = UIColor.init(red: self.delegate.redColor,
fxd

2019-04-03 17:18 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        UIGraphicsEndImageContext() // image ends
Не уверен, что сделал правильно но получилось вот так
        guard let context = UIGraphicsGetCurrentContext() else { return }
        defer { UIGraphicsEndImageContext() }

2019-04-03 17:19 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        context?.move(to: fromPoint)
fxd

2019-04-03 17:26 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        UIGraphicsEndImageContext() // image ends
неправильно. defer срабатывает при выходе из функции. Если до него сработает гвард, то и дефера никакого не будет. если ты открыл контекст, то сразу же под ним пишешь дефер, функция его цепляет и при любом выходе из функции запустит код, который внутри него. Для чего сделано: допустим у тебя 3 гвардии ниже по коду. Так бы тебе пришлось в каждом гварде закрывать контекст. А с помощью дефиса ты это сделал 1 раз и забыл

2019-04-03 17:29 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        UIGraphicsEndImageContext() // image ends
Пример: 
UIGraphicsEndImageContext()
defer { UIGraphicsEndImageContext() }

some code 
some code 
some code 
guard .....
some code 
some code 
some code 
guard ... 
some code 
some code 

а без дефера ты бы делал так:

UIGraphicsEndImageContext()

some code 
some code 
some code 
guard ..... else { 
    UIGraphicsEndImageContext() 
    return
}
some code 
some code 
some code 
guard ... else {
    UIGraphicsEndImageContext()
    return
}
some code 
some code 
UIGraphicsEndImageContext()

2019-04-03 17:35 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        var imageRect = CGRect(x: 0, y: 0, width: mainView.frame.width, height: mainView.frame.height)
разные входные параметры в одном случае принимает UIview в другом CGrect

2019-04-03 17:49 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        UIGraphicsEndImageContext() // image ends
понял 
fxd

2019-04-03 17:49 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        imageRect = imageRect.integral
fxd

2019-04-03 17:57 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        var imageRect = CGRect(x: 0, y: 0, width: mainView.frame.width, height: mainView.frame.height)
У любого view есть frame ;)

2019-04-03 17:58 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        mainView.image?.draw(in: imageRect, blendMode: .normal, alpha: 1)
fxd

2019-04-03 18:00 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        var imageRect = CGRect(x: 0, y: 0, width: mainView.frame.width, height: mainView.frame.height)
Осталась 1 строчка, ее пихаем в функцию? 
let imageRect = CGRect(x: 0, y: 0, width: mainView.frame.width, height: mainView.frame.height).integral

2019-04-03 18:26 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        let color = UIColor.init(red: self.delegate.redColor,
fxd

2019-04-03 18:31 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        var imageRect = CGRect(x: 0, y: 0, width: self.frame.width, height: self.frame.height)
переделал в 1 строчку

2019-04-03 18:31 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        UIGraphicsEndImageContext() // image ends
fxd через defer

2019-04-03 18:32 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +    var lastPoint  =  CGPoint()
fxd

2019-04-03 18:34 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +class ViewController: UIViewController, DrawingViewDelegate {
fxd

2019-04-03 18:48 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +class ViewController: UIViewController, DrawingViewDelegate {
fxd если я правильно понял

2019-04-03 18:53 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +    var redColor   =  CGFloat()
fxd redColorSaturation

2019-04-03 18:53 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +
fxd

2019-04-03 18:54 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +            self.view.backgroundColor = UIColor.init(patternImage: image)
fxd

2019-04-03 18:57 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +    func addGestureRecognizer(direction: UISwipeGestureRecognizer.Direction) {
fxd

2019-04-03 18:59 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        default:
fxd         case .down:

2019-04-03 19:00 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        swiped = false
fxd

2019-04-03 19:02 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        let touch = touches.first!
fxd         guard let touch = touches.first else { return }

2019-04-03 19:11 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        let currentPoint = touch.location(in: tempDrawingView)
не знаю насколько это правильно. 
Вывел в функцию с возвратом опционального значения, а потом проверка через гвард guard let touch = getTouch(from: touches) else { return }

2019-04-03 19:14 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        opacityValue.text = String.init(format: "%1.1f", opacity)
fxd

2019-04-03 19:19 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        refreshValues()
тут не понял как сделать :(

2019-04-03 21:20 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        var imageRect = CGRect(x: 0, y: 0, width: mainView.frame.width, height: mainView.frame.height)
Ну такое уже не обязательно вносить

2019-04-04 19:50 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +    var blueColorSaturation:  CGFloat  { get set }
Вот нафига тут все эти параметры? Зачем они set? почему вместо всего этого просто сразу не отдавать color? Для других целей они все равно тут не используются

2019-04-04 19:50 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +    var delegate: DrawingViewColorSource! = nil
какой же он delegate? не обманывай.

2019-04-04 19:50 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +    var delegate: DrawingViewColorSource! = nil
а retain cycle тут случаем не будет?

2019-04-04 19:50 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +
а что делает эта функция?

2019-04-04 19:50 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +    func makeColor() -> CGColor {
какя и сказал, можно это утащить в colorSource и можно это сделать computed property

2019-04-04 19:50 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        image?.draw(in: imageRect)
а если это не выполнится, дальнейший код надо выполнять?

2019-04-04 19:50 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +extension ViewController: DrawingViewColorSource {
вот не правильно ты меня понял. все что дожжен делать этот протокол, должно быть внутри. Но там не могут работать сторед проперти. Нужно придумать решение. можем завтра обсудить голосом если что.

2019-04-04 19:50 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +    // MARK: - DrawingViewDelegate
а вот и  не delegate

2019-04-04 19:50 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        if let touch = touches.first {
return touches.first сделает тоже самое. Но в таком раскладе и правда не стоит выносить это в отдельную функцию.

2019-04-04 19:50 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        if let touch = touches.first {
Я имел ввиду такую функцию: 

func getPoint(touches: Set<UITouch>) -> CGPoint? {
    let touch = getTouch(from: touches) 
    return touch?.location(in: tempDrawingView)
}

2019-04-04 19:53 UTC, AktuBuct requested changes

2019-04-04 19:53 UTC, AktuBuct commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        refreshValues()
ну например тэги расставить для контролов, тогда будешь знать, к какому параметру это относится, но пофиг, это можешь не делать.

2019-04-05 17:09 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +        if let touch = touches.first {
fxd

2019-04-05 17:09 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +    // MARK: - DrawingViewDelegate
fxd

2019-04-05 17:09 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/ViewController.swift
> +extension ViewController: DrawingViewColorSource {
fxd

2019-04-05 17:14 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +        image?.draw(in: imageRect)
fxd

2019-04-05 17:14 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +    func makeColor() -> CGColor {
fxd

2019-04-05 17:14 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +
deleted

2019-04-05 17:14 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +    var delegate: DrawingViewColorSource! = nil
fxd

2019-04-05 17:15 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +    var delegate: DrawingViewColorSource! = nil
fxd

2019-04-05 17:15 UTC, ikirillfedorov commented on HW 24 Drawing Superman/HW 24 Drawing Superman/DrawingView.swift
> +    var blueColorSaturation:  CGFloat  { get set }
fxd

2019-04-05 17:22 UTC, merged